linkPrefix = "/docs/contracts"
name = "@bzxnetwork/contracts"
license = "Apache-2.0"
version = "0.3.4"
description = "Smart contracts for the bZx protocol and external integrations"
author = "bZeroX LLC 2018"
buildTime = 2018-12-15T18:31:42.470Z
target = "scripts/doxity"
src = "contracts/*"
dir = "pages/docs"
source = "https://github.com/DigixGlobal/doxity-gatsby-starter-project/archive/a4886b7a7a04c018ac04fed3125d7d4785e74bed.tar.gz"
out = "./_book"
homepage = "https://bzx.network/docs/"

[interaction]